package com.liga.internship.client.bot;

public enum BotState {
    FILLING_PROFILE_ASK_NAME,
    FILLING_PROFILE_ASK_AGE,
    FILLING_PROFILE_ASK_GENDER,
    FILLING_PROFILE_ASK_DESCRIBE,
    FILLING_PROFILE_ASK_LOOK,
    FILLING_PROFILE_START,
    FILLING_PROFILE_COMPLETE,

    SHOW_USER_PROFILE,
    SHOW_MAIN_MENU,
    SHOW_USER_FAVORITES,
    SHOW_NEXT_FAVORITE,
    SHOW_PREV_FAVORITE,

    START_TINDER,
    CONTINUE_VOTING,
    STOP_VOTING, LOGIN,
}
